# .github/workflows/ci.yml
name: CI for Nuxt 3

# Trigger the workflow on push to the main branch or pull requests
on:
  push:
    branches:
      - main  # Change to the default branch of your project
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Nuxt 3 requires Node.js 16.x or higher

      # Step 3: Cache node_modules to speed up subsequent builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run tests (if you have unit tests configured)
      - name: Run tests
        run: npm test  # Adjust this if your test script is different

      # Step 6: Build the Nuxt 3 project
      - name: Build the project
        run: npm run build

      # Step 7: Upload build artifacts (optional, for debugging or reference)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-dist
          path: .output/  # This is where Nuxt builds its files